services:
   byteout.quiz.admin.quiz:
      class: Byteout\QuizBundle\Admin\QuizAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "Content", label: "Quiz" }
      arguments: [null, Byteout\QuizBundle\Entity\Quiz, null]
